### ISSUE TITLE
Search results include only one Part of Speech

### ISSUE THREAD

**Issue by rektdeckard** [open-language/wordnets#1]
Hey there, first of thanks for the library! 100x easier than scripting with the WordNet CLI, and perfect for my use-case.

I noticed that results from `searchFor` and `searchSimpleFor` queries include only those from a single `pos`, though you'd expect matches from all types. For example, `searchFor(['smart'])` results in:

```js
Map(1) {
  'smart' => {
    lemma: 'smart',
    pos: 'noun',
    offsetCount: 1,
    pointerCount: 2,
    pointers: [
      { symbol: 'Hypernym', offset: 0, pos: 'noun' },
      { symbol: 'Derivationally related form', offset: 0, pos: 'noun' }
    ],
    senseCount: 1,
    tagSenseCount: 0,
    offsets: [ 14355278 ],
    isComment: false,
    offsetData: [
      {
        offset: 14355278,
        pos: 'noun',
        wordCount: 3,
        words: [ 'smart', 'smarting', 'smartness' ],
        pointerCnt: 5,
        pointers: [
          { symbol: 'Hypernym', offset: 14346126, pos: 'noun' },
          { symbol: '+', offset: 1517459, pos: 'adjective' },
          {
            symbol: 'Derivationally related form',
            offset: 2126629,
            pos: 'verb'
          },
          { symbol: '+', offset: 1517459, pos: 'adjective' },
          {
            symbol: 'Derivationally related form',
            offset: 2126629,
            pos: 'verb'
          }
        ],
        glossary: [
          'a kind of pain such as that caused by a wound or a burn or a sore'
        ],
        isComment: false
      }
    ]
  }
}
```

This represents only the **noun** senses of the word, though clearly by looking in the database files, there are **verb** and **adjective** senses as well. For example, `searchOffsetsInDataFor([01338411])` results in:

```js
Map(1) {
  1338411 => {
    offset: 1338411,
    pos: 'adjective satellite',
    wordCount: 2,
    words: [ 'bright', 'smart' ],
    pointerCnt: 3,
    pointers: [
      { symbol: 'Similar to', offset: 1337350, pos: 'adjective' },
      {
        symbol: 'Derivationally related form',
        offset: 5628738,
        pos: 'noun'
      },
      {
        symbol: 'Derivationally related form',
        offset: 5628738,
        pos: 'noun'
      }
    ],
    glossary: [
      'characterized by quickness and ease in learning',
      '"some children are brighter in one subject than another"',
      '"smart children talk earlier than the average"'
    ],
    isComment: false
  }
}
```

Which seems like it should be the most common and obvious sense of the word **smart**. By default, the WordNet CLI returns all senses of all parts of speech when using the `-over` flag -- could you replicate this behavior in this library? Or is it already a feature and I'm just using it wrong?

**Comment by rektdeckard** [comment]
@sudhanshuraheja Also wanted to note I'm using `en-dictionary@1.2.4` and `en-wordnet@2.0.6`, apologies if this issue has already been resolved here, but it doesn't look like it.

**Comment by sudhanshuraheja** [comment]
@rektdeckard will look it up this weekend and update, looks like a bug.

**Comment by rektdeckard** [comment]
@sudhanshuraheja Not sure if you've taken a look at this yet, but I think you are overwriting entries in the lemmaIndex [here](https://github.com/open-language/en-dictionary/blob/4565dbd8fe00753d8a189ef5fbc1e2d10632cb9a/src/database/index.ts#L43) each time you parse an additional database filetype. Instead of being a `Map<string, Index>` I would expect indexLemmaIndex to be a `Map<string, Index[]>`, with potentially an `Index` from each the database files. 

I can accumulate the expected parts of speech by just doing:
```js
this.indexLemmaIndex.set(index.lemma, [...this.indexLemmaIndex.get(index.lemma) || [], index]);
```

**Comment by rektdeckard** [comment]
Might be a nice API to manage records of different parts of speech like so:
````js
type Pos = "adj" | "adv" | "noun" | "verb";

declare class Database {
  path: string;
  isReady: boolean;
  index: Index[];
  indexLemmaIndex: Map<string, Map<Pos, Index>>
  ...
}
